### ISSUE TITLE
Display rainfall data in a human readable format

### ISSUE THREAD

**Issue by salekd** [sensemakersamsterdam/sensemakers-iot-platform#1]
Show rainfall data in mm per day and mm per hour.

**Comment by salekd** [comment]
Update the query below in the following way:
- normalise to the actual bucket size
- use sum over 1 day or 1 hour

```
select 1000000000/elapsed("difference") from (select * from (select difference("rain_counter") from gauge001) where difference=1)
```

**Comment by salekd** [comment]
New dashboard is in place https://grafana.sensemakersams.org/d/L8fQTXiZz/rain-gauge?orgId=1

The mm/hour and mm/day plots need to be normalised properly. @gmos and @tvdtogt, what is the size of the bucket?

**Comment by gmos** [comment]
If I remember correctly Ted said 2 ml.
But you also need the area of the feeding funnel to get to rainfall in  mm/unit_of_time.

If I remember correctly Ted said that on bucket flip corresponds to 2 mm rainfall.  But we need to check. 12/6 on the afternoon I saw several buckets per minute.  2 mm is a bit on the high side I think.  Perhaps it is 0.2 mm.

Ted, can you add the gauges documentation URL to the documentation perhaps?

**Comment by salekd** [comment]
https://github.com/sensemakersamsterdam/sensemakers-iot-platform/commit/5eeacfa26f924c395cf9c1d388f133aa934162e2#diff-126c4c3261a922d852dd22f709c392aa
